version: "3"
services:
    node-app:
        build:
            context: .
            target: devlopment
        volumes:
            - ./src:/app/src:ro
        environment:
            - NODE_ENV=development
        command: npm start
        





      